from pathlib import Path
import re,json,base64
source=Path('src/shell/startup/StartupRoot.svelte').read_text()
styles=re.search(r'<style>([\s\S]*?)</style>',source).group(1)
tokens=Path('src/styles/tokens.css').read_text()
fonts=Path('src/styles/fonts.css').read_text()
fonts=re.sub(r'url\("(.*?)"\)',lambda m:'url("data:font/woff2;base64,'+base64.b64encode((Path('src/styles')/m[1]).resolve().read_bytes()).decode()+'")',fonts)
subtitle=re.search(r'\? "(Preparing your content.*?)"',source).group(1)
initial=re.search(r'let phase = "(.*?)";',source).group(1)
rows=[
('initial',initial,'Mount the bundled startup screen; initialize/read diagnostics.','src/shell/startup/StartupRoot.svelte:31','Every launch'),
('verify-installed','Verifying installed content…','Ask the native startup loader for the selected trusted content generation.','src/shell/startup/StartupRoot.svelte:101','Every launch'),
('installation','installation (0/4)…','Install a missing trusted generation from bundled resources.','src-tauri/src/native_startup.rs:265','Only when the trusted generation is absent; example package count'),
('source-copy','source and media copy (256 files)…','Copy readable authoring files and optional media once; preserve existing files.','src-tauri/src/native_startup.rs:232','First installation only; illustrative copied-file count'),
('verification','verification (0/6)…','Read selected critical JSON snapshots, hash and parse the same bytes.','src-tauri/src/native_startup.rs:329','Every launch; example totals include four packages and two engine resources'),
('engine','engine preparation (4/6)…','Read and verify frozen WASM and its vendor manifest. The actual Worker is prepared later.','src-tauri/src/native_startup.rs:384','Every launch; illustrative counter'),
('users','user state (0/1)…','Acquire the exclusive writer and initialize current user JSON in memory.','src/storage/native/prepared-storage.ts:180','Every launch'),
('mods','mod composition (0/2)…','Read/validate enabled mods and apply explicit additions/overrides.','src/storage/native/prepared-storage.ts:203','Modded mode only; illustrative enabled-mod count'),
('projections','domain projections (0/1)…','Build the resident snapshot catalog and media mappings.','src/storage/native/prepared-storage.ts:273','Every launch'),
('gameplay','Preparing gameplay and screens…','Prepare Freeplay and every active chapter, search indexes, common screen modules and the duel Worker. Publish Ready only after all requirements succeed.','src/shell/startup/StartupRoot.svelte:108','Every launch'),
('cancelled','Startup cancelled','Explicit cancellation leaves the startup surface and recovery controls available.','src/shell/startup/StartupRoot.svelte:136','Cancellation example'),
('failed','Application could not start','Critical startup failure blocks Main Menu and shows source-located diagnostics.','src/shell/startup/StartupRoot.svelte:137','Failure example'),
]
rows=[dict(id=a,title=b,context=c,source=d,when=e) for a,b,c,d,e in rows]
framecss=tokens+'\n'+fonts+'\n:root{font-family:var(--font-ui);color:var(--text);background:var(--bg);font-synthesis:none;text-rendering:optimizeLegibility}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% -10%,var(--field-glow) 0,transparent 35rem),var(--bg)}\n'+styles
base='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Startup copy workbench</title><style>__TOKENS__
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.5 system-ui,sans-serif}header{padding:20px 24px;border-bottom:1px solid var(--border-soft)}h1{margin:0;font-size:24px}header p{margin:6px 0 0;color:var(--muted)}.layout{display:grid;grid-template-columns:340px minmax(0,1fr);min-height:calc(100svh - 130px)}aside{padding:22px;border-right:1px solid var(--border-soft);display:flex;flex-direction:column;gap:16px}label{display:block;font-weight:600;margin-bottom:6px}select,input,textarea,button{font:inherit;color:var(--text);background:var(--surface);border:1px solid var(--border);border-radius:3px;min-height:44px;padding:8px 10px;width:100%}textarea{min-height:90px;resize:vertical}button{cursor:pointer}button:hover{border-color:var(--accent)}:focus-visible{outline:2px solid var(--accent);outline-offset:3px}.pair{display:flex;gap:10px}.hint{color:var(--muted);font-size:14px;margin:0}.source{overflow-wrap:anywhere;font:13px/1.5 monospace;color:var(--accent)}.stage{padding:24px;overflow:auto}.frame-wrap{width:max-content;max-width:none;box-shadow:0 0 0 1px var(--border)}iframe{display:block;border:0;background:var(--bg)}.notice{margin:0 0 16px;color:var(--muted);max-width:65ch}#status{min-height:24px;color:var(--accent)}@media(max-width:850px){.layout{grid-template-columns:1fr}aside{border-right:0;border-bottom:1px solid var(--border-soft)}.stage{padding:16px}}@media(prefers-reduced-motion:no-preference){button{transition:border-color .15s}}
</style></head><body><header><h1>Startup copy workbench</h1><p>Hold any startup state on screen and try wording in context. Preview edits stay here; the application and saves remain unchanged.</p></header><main class="layout"><aside><div><label for="state">Startup state</label><select id="state"></select></div><div class="pair"><button id="previous">Previous</button><button id="next">Next</button></div><div><label for="heading">Heading draft</label><textarea id="heading"></textarea></div><div><label for="subtitle">Supporting text draft</label><textarea id="subtitle"></textarea></div><div><label for="viewport">Preview size</label><select id="viewport"><option value="1280,800">Desktop · 1280 × 800</option><option value="820,600" selected>Compact · 820 × 600</option><option value="390,844">Mobile reference · 390 × 844</option></select></div><div><p id="context"></p><p id="when" class="hint"></p><p id="source" class="source"></p></div><button id="reset">Reset this state</button><button id="export">Download copy drafts</button><p id="status" role="status"></p><p class="hint">Current technical phase IDs are displayed with hyphens changed to spaces. Counters here are simulated examples. Mobile sizing is a layout reference, not physical-device acceptance. Recreated card uses current startup CSS/tokens and embedded fonts; this is not a live Tauri startup.</p></aside><section class="stage"><p class="notice">The framed area reproduces the current startup card. Controls inside it simulate recovery; they do not read files, restart the app or open logs.</p><div class="frame-wrap"><iframe id="frame" title="Startup state preview"></iframe></div></section></main><script>
const states=__ROWS__;const subtitle=__SUBTITLE__;const framecss=__FRAMECSS__;const $=id=>document.getElementById(id);const drafts={};
for(const s of states){drafts[s.id]={heading:s.title,subtitle:['failed','cancelled'].includes(s.id)?'1 startup error':subtitle};const o=document.createElement('option');o.value=s.id;o.textContent=s.title;$('state').append(o);}
function active(){return states.find(s=>s.id===$('state').value)}
function escape(t){return t.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const s=active(),d=drafts[s.id],failure=['failed','cancelled'].includes(s.id);const diagnostic=failure?'<ol><li><strong>'+(s.id==='failed'?'BASE_HASH_MISMATCH':'OPERATION_CANCELLED')+'</strong><p>'+(s.id==='failed'?'Critical snapshot digest mismatch.':'Startup was cancelled.')+'</p><pre>Example fixture: card-library/critical.json</pre><p>'+(s.id==='failed'?'Repair the named critical snapshot from the bundled trusted release, then retry.':'Correct the reported content or user-data problem, then retry. Your saves have not been removed.')+'</p></li></ol>':'';
const actions=failure?'<div class="actions">'+(s.id==='failed'?'<button data-action="repair">Repair bundled critical content and retry</button>':'')+'<button data-action="retry">Retry</button><button disabled>Open log</button><button disabled>Open log folder</button><button data-action="copy">Copy details</button><button disabled>Copy log path</button><button data-action="copy">Export details</button><button data-action="quit">Quit</button></div>':'<button data-action="cancel">Cancel startup</button>';
$('frame').srcdoc='<!doctype html><html lang="en"><head><meta charset="utf-8"><style>'+framecss+'</style></head><body><main class="startup" aria-busy="'+!failure+'"><section class="panel"><h1>'+escape(d.heading)+'</h1><p role="status">'+escape(d.subtitle)+'</p>'+diagnostic+actions+'</section></main></body></html>';
const [w,h]=$('viewport').value.split(',');$('frame').width=w;$('frame').height=h;}
function choose(){const s=active();$('heading').value=drafts[s.id].heading;$('subtitle').value=drafts[s.id].subtitle;$('context').textContent=s.context;$('when').textContent=s.when;$('source').textContent=s.source;$('status').textContent='';render()}
$('state').onchange=choose;$('viewport').onchange=render;for(const id of ['heading','subtitle'])$(id).oninput=()=>{drafts[active().id][id]=$ (id).value;render()};
function step(n){$('state').selectedIndex=($('state').selectedIndex+n+states.length)%states.length;choose()};$('previous').onclick=()=>step(-1);$('next').onclick=()=>step(1);
$('reset').onclick=()=>{const s=active();drafts[s.id]={heading:s.title,subtitle:['failed','cancelled'].includes(s.id)?'1 startup error':subtitle};choose()};
$('export').onclick=()=>{const bytes=new Blob([JSON.stringify({kind:'startup-copy-drafts',source:'Reference preview 2026-10-04',drafts},null,2)],{type:'application/json'});const url=URL.createObjectURL(bytes);const a=document.createElement('a');a.href=url;a.download='startup-copy-drafts.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='Drafts downloaded; production copy unchanged.'};
$('frame').onload=()=>{for(const b of $('frame').contentDocument.querySelectorAll('[data-action]'))b.onclick=()=>{const action=b.dataset.action;if(action==='cancel')$('state').value='cancelled';else if(action==='retry'||action==='repair')$('state').value='initial';else{$('status').textContent='Preview only: no native action performed.';return}choose()}};choose();
</script></body></html>'''
html=base.replace('__TOKENS__',tokens).replace('__ROWS__',json.dumps(rows)).replace('__SUBTITLE__',json.dumps(subtitle)).replace('__FRAMECSS__',json.dumps(framecss))
p=Path('artifacts/STARTUP_COPY_WORKBENCH_2026_10_04.html')
with p.open('x') as f:f.write(html)
print(f'{len(rows)} state previews; {len(html.encode())} bytes; fonts embedded, no external requests.')
