from pathlib import Path
import json
scripts=json.loads(Path('package.json').read_text())['scripts']
desc={
'legacy:assets:inventory':'Scan legacy roots/profiles into an inventory; `--check` checks without writing.',
'legacy:assets:profile-promote':'Preview profile delivery-rule changes; `--apply` writes them. No asset moves or publishing.',
'legacy:assets:copy-migrate':'Plan/apply hash-guarded copies from historical asset layouts; originals preserved.',
'legacy:assets:copy-to-package-roots':'Plan/apply historical asset copies into package-owned roots.',
'assets:bootstrap':'Acquire/verify the pinned engine and upstream card/script/string sources; acquire full/cropped card images online; verify full images and generate/verify a source manifest. Set images, card-back art and JSON release staging are separate.',
'assets:engine:acquire':'Acquire the pinned engine into tooling storage; does not update frozen vendor files.',
'assets:engine:verify-acquired':'Check the acquired engine files against their manifest and WASM header.',
'assets:upstream:sync':'Synchronize pinned upstream card/script/string sources and generate acquisition data. Pass `-- --offline` to use local caches without fetching.',
'assets:verify-all':'Verify acquisition data, set images and the full-card image archive.',
'assets:cards:download-full':'Download/resume full-card JPEG artwork.',
'assets:cards:download-cropped':'Download/resume cropped card illustrations.',
'assets:cards:download-cropped-reviewed-pool':'Download crops only for the reviewed deck card pool; this is not the installed-content selection.',
'assets:cards:verify-full':'Verify full-card archive coverage, JPEG boundaries and download-report consistency; does not verify cropped art.',
'assets:card-back:download':'Download optional card-back artwork.',
'assets:sets:download-images':'Acquire set artwork and write its manifest.',
'assets:sets:verify-images':'Verify set artwork and the reviewed image lock.',
'assets:images:pin':'Generate the tracked image digest lock from local shipped card/crop/set artwork; review changes before accepting them.',
'vendor:verify':'Verify frozen vendored engine files against their reviewed manifest.',
'content:source-manifest:generate':'Generate the acquisition/runtime-source manifest. This does not compile ADR-104 critical JSON snapshots.',
'content:source-manifest:verify':'Independently derive and verify the acquisition/runtime-source manifest and files.',
'content:shop-sets:fetch-and-generate':'Fetch provider card membership for 50 TCG sets and write shop-set authoring JSON.',
'frontend:dev':'Start Vite only; native application development uses `native:desktop:dev`.',
'frontend:build':'Verify vendor files, bundle frontend code and verify artifact boundaries/budgets. Output: `generated/build/app/`. Does not build a native executable.',
'frontend:bundle':'Run Vite in native frontend mode without the surrounding vendor/artifact checks.',
'frontend:verify':'Check the generated frontend artifact, public build boundaries and domain byte budgets.',
'frontend:verify-reproducible':'Build twice into isolated output directories and require identical file hashes.',
'frontend:preview':'Serve existing built frontend files for inspection/browser fixtures; does not launch Tauri.',
'format':'Apply Prettier to the configured source, test, script and root-config files.',
'format:check':'Check Prettier without rewriting files.',
'lint':'Run ESLint.',
'typecheck':'Run TypeScript and Svelte type checks.',
'test:tooling':'Run Node tests under `tests/*.test.ts`, including acquisition and migration tooling.',
'test:unit-and-performance':'Run Vitest unit tests, then the separately isolated deck-catalog performance suite.',
'test:component':'Run Svelte component tests.',
'test:integration':'Run integration tests, including real engine/assets where fixtures require them.',
'test:browser:native-bridge':'Run Playwright native-IPC browser fixtures using Chromium/WebKit projects. Does not launch a native desktop executable.',
'test:browser:visual-acceptance':'Run the isolated Chromium visual acceptance harness.',
'test':'Run tooling, unit/performance, component and integration tests. Excludes browser, Rust and actual native desktop/physical acceptance.',
'check:headless':'Check formatting/lint/types; run tooling, unit/performance and integration tests; verify vendor, acquisition assets and source manifest. Component tests are in the separate frontend/browser gate.',
'check:frontend-and-browser':'Run component tests, frontend build/verification/reproducibility and both browser suites.',
'check':'Run both preceding check groups. Excludes Rust, SQLite/JSON parity and actual native desktop/physical acceptance.',
'content:convert:sqlite-to-json':'Convert a verified historical SQLite package to readable JSON sources and independent media: `-- <input.sqlite> <new-source-directory>`.',
'content:compile:json':'Compile readable sources to critical JSON, source maps and engine digests: `-- <source-directory> <output-directory>`.',
'content:verify:sqlite-json-parity':'Compare historical SQLite queries against JSON snapshot queries and check repeatable compilation.',
'mods:bundle':'Bundle declared mod files into a new JSON import file: `-- <mod-directory> <new-bundle.json>`. Startup still performs Lua/composition validation.',
'mods:audit:wasm-imports':'Inspect frozen WASM imports and loader bindings; write a new report: `-- <new-report.json>`. Not a general proof of script safety.',
'legacy:content:export-sqlite':'Produce historical SQLite content packages: `-- --spec <file>`.',
'legacy:content:verify-sqlite':'Verify one historical SQLite package: `-- --file <file>`; does not prove cross-package stack validity.',
'content:release:pin':'Compile/check source inputs and write tracked `content/critical-release.json`, the application trust anchor. Review the resulting digest changes.',
'content:stage:native':'Compile/check inputs against the pinned release and atomically stage readable native resources.',
'content:stage:verify-native':'Verify staged critical snapshots and frozen engine buffers against the pinned release.',
'content:stage:cleanup':'Preview marked content staging: `-- --target <staging-directory>`. Add `--delete` to delete that stage; installed app-data and saves are outside its scope.',
'native:desktop:dev':'Prepare native content and launch Tauri with Vite development hosting.',
'native:build-and-start:linux':'Build through the Tauri CLI with `--no-bundle`, then launch the Linux executable. Uses bundled frontend assets; no development server required.',
'native:desktop:build':'Run Tauri desktop build/package, including content staging, frontend verification and standalone custom-protocol support. Pass `-- --no-bundle` for an executable without installers.',
'native:android:dev':'Run Tauri Android development; requires the platform toolchain/device.',
'native:android:build':'Build the Tauri Android application; requires the platform toolchain.',
'native:ios:dev':'Run Tauri iOS development on a supported Apple toolchain/device.',
'native:ios:build':'Build the Tauri iOS application on a supported Apple toolchain.',
'test:native:rust':'Run Cargo tests for the native crate. Opt-in ignored instrumentation tests remain separate.',
}
assert set(desc)==set(scripts),(set(scripts)-set(desc),set(desc)-set(scripts))
p=Path('docs/development-commands.md')
with p.open('x') as f:
 f.write('# Development commands\n\nUse Node 26 or newer. `package.json` is the executable command registry. Names distinguish frontend files, native applications, source acquisition, JSON release content, browser fixtures and retained legacy conversion.\n\nFor an ordinary Linux launch, use `npm run native:build-and-start:linux`. Preserve an already-running owner session. Unset acceptance/recovery instrumentation variables for ordinary launches. A plain Cargo release build can still target the development URL; standalone launches require Tauri custom-protocol support.\n\nPass command arguments after `--`. Conversion and compilation accept `--help`. Legacy commands remain available for historical recovery; they do not define the current gameplay content authority.\n\n| ID | Command | Scope |\n| --- | --- | --- |\n')
 for i,name in enumerate(scripts,1):f.write(f'| C{i} | `npm run {name}` | {desc[name]} |\n')
 f.write('\n`npm test` is equivalent to `npm run test`. Aggregate checks intentionally retain their existing coverage; a successful `check` is not native Rust, actual desktop, external-opener or physical-device acceptance.\n\nActual desktop recovery uses `node scripts/verify-native-startup-recovery.ts <new-report.json>` with the isolated opt-in native-acceptance build. See [startup I/O evidence](architecture/06-quality/startup-io-evidence.md) for instrumentation and capture limits.\n')
print('Complete reference covers all 60 commands.')
