/* The vocabulary the visual novel and the shell share about one duel. The
   story never mounts a duel and never imports the battle facade; it types the
   result it will be handed, and normalises it into the four authored outcome
   branches it already had. */

import type { BattleFacadeResult } from "../../battle/battle-contracts.ts";
import type {
  BattleResult,
  LocationId as EncounterId,
  StoryState,
} from "../model/story-state.ts";

/** One duel the shell is about to run for the story. The id is opaque and
    generated by the shell, which is the only side that can address a route. */
export interface StoryEncounterIntent {
  readonly handoffId: string;
  readonly encounterId: EncounterId;
  readonly label: string;
}

/** What the story hands upwards when the player starts an encounter. It is the
    intent minus the handoff id, plus the state to checkpoint: the story cannot
    name a route, and the shell cannot know which beat the player is on. */
export interface StoryEncounterRequest {
  readonly encounterId: EncounterId;
  readonly label: string;
  readonly state: StoryState;
}

/** Whether the duel actually started. A checkpoint that could not be written
    and verified never becomes a duel — the story shows a retry instead. */
export type StoryHandoffOutcome = "ready" | "checkpoint-failed";

/** The duel the story is waiting on. Exactly one exists at a time. */
export interface PendingStoryDuel {
  readonly handoffId: string;
  readonly encounterId: EncounterId;
}

export type StoryDuelResolution =
  | { readonly kind: "win" }
  | { readonly kind: "loss" }
  | { readonly kind: "abort" }
  | { readonly kind: "failure"; readonly message: string };

/** The opponent each map node stages, shown while the duel is being prepared.
    The map's own place names stay with the map screen; this is the encounter. */
export const ENCOUNTER_LABELS: Readonly<Record<EncounterId, string>> =
  Object.freeze({
    "old-arena": "Rin's Echo",
    archive: "Archive echo",
    "hidden-gate": "Hidden gate echo",
  });

/**
 * Normalises a duel's own ending into the story's authored branches.
 *
 * Two mappings carry the weight. A technical stop is `failure` and never a
 * loss: a duel the engine could not finish must not advance the story past a
 * defeat it never dealt. A draw takes the loss branch — the authored loss
 * scene reads as "the duel completed, and completing it was the point", which
 * is exactly what a draw is; the win branch is reserved for a win.
 */
export function toStoryResolution(
  result: BattleFacadeResult,
): StoryDuelResolution {
  switch (result.kind) {
    case "resolved":
      return result.outcome === "player-win"
        ? { kind: "win" }
        : { kind: "loss" };
    case "aborted":
      return { kind: "abort" };
    case "failed":
      return { kind: "failure", message: result.message };
  }
}

/** The reducer command branch a resolution belongs to. */
export function storyBattleResult(
  resolution: StoryDuelResolution,
): BattleResult {
  switch (resolution.kind) {
    case "win":
      return "win";
    case "loss":
      return "loss";
    case "abort":
      return "abort";
    case "failure":
      return "failure";
  }
}

/** Fills in the handoff fields a save written before this slice existed does
    not carry. Applied wherever a stored state re-enters the app, so an older
    record resumes as "no duel in flight" instead of reading as corrupt or
    leaking `undefined` into a field the rest of the domain treats as set. */
export function restoreStoryState(state: StoryState): StoryState {
  return {
    ...state,
    encounterId: state.encounterId ?? null,
    pendingHandoffId: state.pendingHandoffId ?? null,
  };
}

/** Whether a result belongs to the duel the story is actually waiting on. A
    stale result from a previous encounter, a duplicate of one already taken,
    and a result arriving when nothing is pending all answer `false`. */
export function acceptsResult(
  pending: PendingStoryDuel | null,
  handoffId: string,
): boolean {
  return (
    pending !== null && handoffId !== "" && pending.handoffId === handoffId
  );
}
