/* The vocabulary the visual novel and the shell share about one duel. The
   story never mounts a duel and never imports the battle facade; it types the
   result it will be handed, and normalises it into the four authored outcome
   branches it already had. */

import type { BattleFacadeResult } from "../../battle/battle-contracts.ts";
/* Type-only, like the battle import above: `src/decks/index.ts` reaches the
   deck database and `idb` through it, and the shell's coordinator imports this
   module from its eager entry chunk. */
import type { ValidatedDeckSnapshot } from "../../decks/index.ts";
import type {
  BattleResult,
  EncounterId,
  StoryState,
} from "../model/story-state.ts";

/** One duel the shell is about to run for the story. The id is opaque and
    generated by the shell, which is the only side that can address a route. */
export interface StoryEncounterIntent {
  readonly handoffId: string;
  readonly encounterId: EncounterId;
  readonly label: string;
}

/** What the story hands upwards when the player starts an encounter. It is the
    intent minus the handoff id, plus the state to checkpoint: the story cannot
    name a route, and the shell cannot know which beat the player is on.

    `deck` is the seat the player chose at the briefing, already resolved
    against the live catalog, the pinned ruleset and this save's own ownership.
    It travels beside the state rather than being read back out of it, because
    the shell has none of those three and must not decide legality (ADR-050). */
export interface StoryEncounterRequest {
  readonly encounterId: EncounterId;
  readonly label: string;
  readonly state: StoryState;
  readonly deck: ValidatedDeckSnapshot;
}

/** Whether the duel actually started, and what stopped it when it did not.

    A checkpoint that could not be written and verified never becomes a duel.
    Neither does a deck the duel's own contract refuses — the two are separate
    answers because they need separate ways out: one is storage the player has
    to free, the other is a deck they have to change. */
export type StoryHandoffOutcome =
  "ready" | "checkpoint-failed" | "deck-rejected";

/** The duel the story is waiting on. Exactly one exists at a time. */
export interface PendingStoryDuel {
  readonly handoffId: string;
  readonly encounterId: EncounterId;
}

export type StoryDuelResolution =
  | { readonly kind: "win" }
  | { readonly kind: "loss" }
  | { readonly kind: "abort" }
  | { readonly kind: "failure"; readonly message: string };

/** The opponent each map node stages, shown while the duel is being prepared.
    The map's own place names stay with the map screen; this is the encounter. */
export const ENCOUNTER_LABELS: Readonly<Record<EncounterId, string>> =
  Object.freeze({
    "old-arena": "Rin's Echo",
    archive: "Archive echo",
    "hidden-gate": "Hidden gate echo",
  });

/**
 * Normalises a duel's own ending into the story's authored branches.
 *
 * Two mappings carry the weight. A technical stop is `failure` and never a
 * loss: a duel the engine could not finish must not advance the story past a
 * defeat it never dealt. A draw takes the loss branch — the authored loss
 * scene reads as "the duel completed, and completing it was the point", which
 * is exactly what a draw is; the win branch is reserved for a win.
 */
export function toStoryResolution(
  result: BattleFacadeResult,
): StoryDuelResolution {
  switch (result.kind) {
    case "resolved":
      return result.outcome === "player-win"
        ? { kind: "win" }
        : { kind: "loss" };
    case "aborted":
      return { kind: "abort" };
    case "failed":
      return { kind: "failure", message: result.message };
  }
}

/** The reducer command branch a resolution belongs to. */
export function storyBattleResult(
  resolution: StoryDuelResolution,
): BattleResult {
  switch (resolution.kind) {
    case "win":
      return "win";
    case "loss":
      return "loss";
    case "abort":
      return "abort";
    case "failure":
      return "failure";
  }
}

/** Fills in the handoff fields a save written before this slice existed does
    not carry. Applied wherever a stored state re-enters the app, so an older
    record resumes as "no duel in flight" instead of reading as corrupt or
    leaking `undefined` into a field the rest of the domain treats as set. */
export function restoreStoryState(state: StoryState): StoryState {
  return {
    ...state,
    previousScreen: state.previousScreen ?? null,
    encounterId: state.encounterId ?? null,
    pendingHandoffId: state.pendingHandoffId ?? null,
  };
}

/** Whether a result belongs to the duel the story is actually waiting on. A
    stale result from a previous encounter, a duplicate of one already taken,
    and a result arriving when nothing is pending all answer `false`. */
export function acceptsResult(
  pending: PendingStoryDuel | null,
  handoffId: string,
): boolean {
  return (
    pending !== null && handoffId !== "" && pending.handoffId === handoffId
  );
}
